// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model_gen

import (
	"time"

	"gorm.io/gorm"
)

const TableNameChannel = "channel"

// Channel mapped from table <channel>
type Channel struct {
	ID           int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt    time.Time      `gorm:"column:created_at" json:"createdAt"`
	UpdatedAt    time.Time      `gorm:"column:updated_at" json:"updatedAt"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at" json:"-"`
	Type         string         `gorm:"column:type;not null;comment:类型" json:"type"`         // 类型
	UserID       int64          `gorm:"column:user_id;comment:用户ID" json:"userId"`           // 用户ID
	Configration string         `gorm:"column:configration;comment:配置项" json:"configration"` // 配置项
}

// TableName Channel's table name
func (*Channel) TableName() string {
	return TableNameChannel
}
